"""J2 template renderer from TemplateDefinition.

Design: plan-j2-generate T-GEN-05, DC-0082
"""

from generate.models import TemplateDefinition


def render_j2(template_def: TemplateDefinition) -> str:
    """Render a TemplateDefinition into a .j2 template file content.

    Args:
        template_def: Validated template definition.

    Returns:
        Complete .j2 file content as a string.

    Design: DC-0082
    """
    lines: list[str] = []

    # Header comments — use format() to avoid f-string parsing issues with {#
    lines.append("{# @id %s #}" % template_def.id)
    lines.append("{# @name %s #}" % template_def.name)
    lines.append("{# @description %s #}" % template_def.description)

    for concept in template_def.concepts:
        lines.append('{# @concept "%s" #}' % concept)

    for note in template_def.notes:
        lines.append("{# @note %s #}" % note)

    for ref in template_def.seealso:
        lines.append("{# @seealso %s #}" % ref)

    for err in template_def.common_errors:
        err_text = err.get("error_text", "")
        explanation = err.get("explanation", "")
        lines.append('{# @common_error "%s" — %s #}' % (err_text, explanation))

    for param in template_def.params:
        req = "required" if param.required else "optional"
        default = " default=%s" % param.default if param.default else ""
        lines.append(
            "{# @param %s %s %s %s%s #}"
            % (param.name, param.type, req, param.description, default)
        )

    lines.append("")

    # Command body
    lines.append("@echo off")
    lines.append("REM Generated by GIS Agent")
    lines.append(f"REM Template: {template_def.id}")
    lines.append("")
    lines.append(template_def.command_template)
    lines.append("")
    lines.append("REM Done")
    lines.append("")

    return "\n".join(lines)
